## Preprocessing

In [45]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [46]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

The following ten cells are used to explore tha data more and see what type of data is added and how many

In [47]:
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [48]:
application_df["AFFILIATION"].value_counts()

Independent         18480
CompanySponsored    15705
Family/Parent          64
National               33
Regional               13
Other                   4
Name: AFFILIATION, dtype: int64

In [49]:
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1245        1
C4200        1
C4120        1
C2150        1
C1283        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [50]:
application_df["USE_CASE"].value_counts()

Preservation     28095
ProductDev        5671
CommunityServ      384
Heathcare          146
Other                3
Name: USE_CASE, dtype: int64

In [51]:
application_df["ORGANIZATION"].value_counts()

Trust           23515
Association     10255
Co-operative      486
Corporation        43
Name: ORGANIZATION, dtype: int64

In [52]:
application_df["STATUS"].value_counts()

1    34294
0        5
Name: STATUS, dtype: int64

In [53]:
application_df["SPECIAL_CONSIDERATIONS"].value_counts()

N    34272
Y       27
Name: SPECIAL_CONSIDERATIONS, dtype: int64

In [54]:
#Drop SPECIAL_CONSIDERATIONS and STATUS as they are over 99% in favour of one output
application_df = application_df.drop(["SPECIAL_CONSIDERATIONS", "STATUS"], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [55]:
application_df["INCOME_AMT"].value_counts()

0                24388
25000-99999       3747
100000-499999     3374
1M-5M              955
1-9999             728
10000-24999        543
10M-50M            240
5M-10M             185
50M+               139
Name: INCOME_AMT, dtype: int64

In [56]:
# Check the values of the ask_amt column.
application_df["ASK_AMT"].value_counts()

5000       25398
10478          3
15583          3
6725           3
63981          3
           ...
772556         1
70103          1
27096          1
25049          1
1138700        1
Name: ASK_AMT, Length: 8747, dtype: int64

In [57]:
#A we can see from the length, there are too many different values in this column
len(application_df["ASK_AMT"].value_counts())

8747

In [58]:
# fini=ding the amximum ask_amt
max_ask_amt = max(application_df["ASK_AMT"])
max_ask_amt

8597806340

In [59]:
# I looked at the data to see the complete numbers of the ask amount to then start figuring out the bins
bins = [0,5001,1000001,50000001,100000001,300000001,600000001,1000000001,max_ask_amt]
labels = ["5000 or less", "between 5000 and 1 million", "between 1 million and 50 million", "between 50 million and 100 million", "between 100 million and 300 million", "between 300 million and 600 million", "between 600 million and 1 billion", "above 1 billion",]

In [60]:
application_df["ASK_AMT"] = pd.cut(application_df["ASK_AMT"], bins=bins, labels=labels)

In [61]:
application_df["ASK_AMT"].value_counts()

5000 or less                           25399
between 5000 and 1 million              7323
between 1 million and 50 million        1423
between 50 million and 100 million        53
between 100 million and 300 million       50
above 1 billion                           18
between 300 million and 600 million       18
between 600 million and 1 billion         15
Name: ASK_AMT, dtype: int64

In [62]:
#convert datastype to object from category
application_df["ASK_AMT"] = application_df["ASK_AMT"].astype('object')

In [63]:
#Save Is SUCCESSFUL to y variable as we will delete from dataframe and use in test/split 
y = application_df["IS_SUCCESSFUL"].values.reshape(-1,1)
y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [64]:
#Drop IS_SUCCESSFUL as it will interfere with the calculation

application_df = application_df.drop(["IS_SUCCESSFUL"], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,0,5000 or less
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,between 5000 and 1 million
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,between 5000 and 1 million
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,between 5000 and 1 million
...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000 or less
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000 or less
34297,T5,Independent,C3000,ProductDev,Association,0,5000 or less
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,between 1 million and 50 million

In [65]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
ASK_AMT              8
dtype: int64

In [66]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [67]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = ['T9','T13','T12','T2','T14','T25','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [68]:
application_df.head(50)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,0,5000 or less
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,between 5000 and 1 million
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,between 5000 and 1 million
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,between 5000 and 1 million
5,T3,Independent,C1200,Preservation,Trust,0,5000 or less
6,T3,Independent,C1000,Preservation,Trust,100000-499999,between 5000 and 1 million
7,T3,Independent,C2000,Preservation,Trust,10M-50M,between 1 million and 50 million
8,T7,Independent,C1000,ProductDev,Trust,1-9999,between 5000 and 1 million
9,T5,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
10,T3,Independent,C1200,Preservation,Trust,25000-99999,between 5000 and 1 million
11,T3,Independent,C2000,Preservation,Trust,100000-499999,between 5000 and 1 million
12,T3,CompanySponsored,C1200,Preservation,Association,0,5000 or less
13,T3,Independent,C2700,Preservation,Trust,25000-99999,between 5000 and 1 million
14,T3,Independent,C1000,Preservation,Trust,0,5000 or less
15,T3,Independent,C1200,Preservation,Trust,0,5000 or less
16,T3,Independent,C2000,Preservation,Trust,0,5000 or less
17,T3,Independent,C1000,Heathcare,Trust,50M+,between 50 million and 100 million
18,T3,CompanySponsored,C1000,Preservation,Trust,0,5000 or less
19,T3,CompanySponsored,C1000,Preservation,Trust,100000-499999,between 5000 and 1 million
20,T4,Independent,C3000,ProductDev,Trust,0,5000 or less
21,T3,Independent,C1200,Preservation,Trust,0,5000 or less
22,T3,Independent,C7000,Preservation,Trust,100000-499999,between 5000 and 1 million
23,T4,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
24,T3,CompanySponsored,C1200,Preservation,Trust,0,5000 or less
25,T4,Independent,C3000,ProductDev,Trust,0,5000 or less
26,T3,CompanySponsored,C1000,Preservation,Trust,0,5000 or less
27,T3,CompanySponsored,C2000,Preservation,Trust,25000-99999,between 5000 and 1 million
28,T3,CompanySponsored,C2000,Preservation,Trust,0,5000 or less
29,T6,Independent,C2000,ProductDev,Trust,0,5000 or less
30,T6,Independent,C2000,ProductDev,Trust,100000-499999,between 5000 and 1 million
31,T3,Independent,C1200,Preservation,Trust,0,5000 or less
32,T7,Independent,C1000,ProductDev,Trust,0,5000 or less
33,T3,CompanySponsored,C1000,Preservation,Trust,0,5000 or less
34,T3,Independent,C1000,Preservation,Trust,0,5000 or less
35,T3,Independent,C1200,Preservation,Trust,0,5000 or less
36,T4,Independent,C1000,ProductDev,Trust,0,5000 or less
37,T3,Independent,C1000,Preservation,Trust,0,5000 or less
38,T7,Independent,C1000,ProductDev,Association,0,5000 or less
39,T3,Independent,C1000,Preservation,Trust,25000-99999,5000 or less
40,T3,Independent,C1000,Preservation,Trust,25000-99999,between 5000 and 1 million
41,Other,Independent,C1000,ProductDev,Trust,25000-99999,between 1 million and 50 million
42,T7,Independent,C1000,ProductDev,Trust,0,5000 or less
43,T3,CompanySponsored,C1000,Preservation,Trust,0,5000 or less
44,T3,Independent,C7200,Preservation,Trust,0,5000 or less
45,T3,Independent,C1000,Preservation,Trust,0,5000 or less
46,T3,CompanySponsored,C2000,Preservation,Trust,0,5000 or less
47,T7,Independent,C1000,ProductDev,Trust,0,5000 or less
48,T3,Independent,C1700,Preservation,Trust,0,5000 or less
49,T3,Independent,C1000,Preservation,Trust,0,5000 or less

In [84]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [85]:
# put all values in a list
df_unique_values = application_df['CLASSIFICATION'].unique()
len(df_unique_values)

6

In [86]:
# You may find it helpful to look at CLASSIFICATION value counts >1000
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x > 1000]

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [87]:
# create a list with values_count over 1000
delete_from_array = ["C1000", "C2000","C1200","C3000", "C2100"]
delete_from_array

['C1000', 'C2000', 'C1200', 'C3000', 'C2100']

In [88]:
# remove values from df_unique_values that are in delete_from_array
df_unique_values = [i for i in df_unique_values if i not in delete_from_array]
len(df_unique_values)

1

In [89]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = df_unique_values
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [90]:
application_df.head(5)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,0,5000 or less
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,between 5000 and 1 million
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000 or less
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,between 5000 and 1 million
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,between 5000 and 1 million

In [91]:
# Convert categorical data to numeric with `pd.get_dummies`
# Generate our categorical variable lists

application_df_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_df_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'ASK_AMT']

In [92]:
application_df.dtypes

APPLICATION_TYPE    object
AFFILIATION         object
CLASSIFICATION      object
USE_CASE            object
ORGANIZATION        object
INCOME_AMT          object
ASK_AMT             object
dtype: object

In [93]:
application_df["APPLICATION_TYPE"].values

array(['T10', 'T3', 'T5', ..., 'T3', 'T5', 'T3'], dtype=object)

In [94]:
# Check the number of unique values in each column
application_df[application_df_cat].nunique()

APPLICATION_TYPE    9
AFFILIATION         6
CLASSIFICATION      6
USE_CASE            5
ORGANIZATION        4
INCOME_AMT          9
ASK_AMT             8
dtype: int64

In [95]:
application_df_get_dummies = pd.get_dummies(application_df, columns=application_df_cat)
application_df_get_dummies.columns

Index(['APPLICATION_TYPE_Other', 'APPLICATION_TYPE_T10',
       'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3', 'APPLICATION_TYPE_T4',
       'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6', 'APPLICATION_TYPE_T7',
       'APPLICATION_TYPE_T8', 'AFFILIATION_CompanySponsored',
       'AFFILIATION_Family/Parent', 'AFFILIATION_Independent',
       'AFFILIATION_National', 'AFFILIATION_Other', 'AFFILIATION_Regional',
       'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200', 'CLASSIFICATION_C2000',
       'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000', 'CLASSIFICATION_Other',
       'USE_CASE_CommunityServ', 'USE_CASE_Heathcare', 'USE_CASE_Other',
       'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'ASK_AMT_5000 or less', 'ASK_AMT_above 1 billion',
       'ASK_AMT_between 1 million and 50 million',
       'ASK_AMT_between 100 million and 300 million',
       'ASK_AMT_between 300 million and 600 million',
       'ASK_AMT_between 50 million and 100 million',
       'ASK_AMT_between 5000 and 1 million',
       'ASK_AMT_between 600 million and 1 billion'],
      dtype='object')

In [96]:
application_df_get_dummies.columns

Index(['APPLICATION_TYPE_Other', 'APPLICATION_TYPE_T10',
       'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3', 'APPLICATION_TYPE_T4',
       'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6', 'APPLICATION_TYPE_T7',
       'APPLICATION_TYPE_T8', 'AFFILIATION_CompanySponsored',
       'AFFILIATION_Family/Parent', 'AFFILIATION_Independent',
       'AFFILIATION_National', 'AFFILIATION_Other', 'AFFILIATION_Regional',
       'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200', 'CLASSIFICATION_C2000',
       'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000', 'CLASSIFICATION_Other',
       'USE_CASE_CommunityServ', 'USE_CASE_Heathcare', 'USE_CASE_Other',
       'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'ASK_AMT_5000 or less', 'ASK_AMT_above 1 billion',
       'ASK_AMT_between 1 million and 50 million',
       'ASK_AMT_between 100 million and 300 million',
       'ASK_AMT_between 300 million and 600 million',
       'ASK_AMT_between 50 million and 100 million',
       'ASK_AMT_between 5000 and 1 million',
       'ASK_AMT_between 600 million and 1 billion'],
      dtype='object')

In [101]:
#Input dimensions
len(application_df_get_dummies.columns)

47

In [102]:
application_df_concat = pd.concat([application_df, application_df_get_dummies], axis=1)
application_df_concat_list = application_df_concat.columns.tolist()
application_df_concat_list

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'ASK_AMT',
 'APPLICATION_TYPE_Other',
 'APPLICATION_TYPE_T10',
 'APPLICATION_TYPE_T19',
 'APPLICATION_TYPE_T3',
 'APPLICATION_TYPE_T4',
 'APPLICATION_TYPE_T5',
 'APPLICATION_TYPE_T6',
 'APPLICATION_TYPE_T7',
 'APPLICATION_TYPE_T8',
 'AFFILIATION_CompanySponsored',
 'AFFILIATION_Family/Parent',
 'AFFILIATION_Independent',
 'AFFILIATION_National',
 'AFFILIATION_Other',
 'AFFILIATION_Regional',
 'CLASSIFICATION_C1000',
 'CLASSIFICATION_C1200',
 'CLASSIFICATION_C2000',
 'CLASSIFICATION_C2100',
 'CLASSIFICATION_C3000',
 'CLASSIFICATION_Other',
 'USE_CASE_CommunityServ',
 'USE_CASE_Heathcare',
 'USE_CASE_Other',
 'USE_CASE_Preservation',
 'USE_CASE_ProductDev',
 'ORGANIZATION_Association',
 'ORGANIZATION_Co-operative',
 'ORGANIZATION_Corporation',
 'ORGANIZATION_Trust',
 'INCOME_AMT_0',
 'INCOME_AMT_1-9999',
 'INCOME_AMT_10000-24999',
 'INCOME_AMT_100000-499999',
 'INCOME_AMT_10M-50M',
 'INCOME_AMT_1M-5M',
 'INCOME_AMT_25000-99999',
 'INCOME_AMT_50M+',
 'INCOME_AMT_5M-10M',
 'ASK_AMT_5000 or less',
 'ASK_AMT_above 1 billion',
 'ASK_AMT_between 1 million and 50 million',
 'ASK_AMT_between 100 million and 300 million',
 'ASK_AMT_between 300 million and 600 million',
 'ASK_AMT_between 50 million and 100 million',
 'ASK_AMT_between 5000 and 1 million',
 'ASK_AMT_between 600 million and 1 billion']

In [112]:
application_df_get_dummies

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,INCOME_AMT_50M+,INCOME_AMT_5M-10M,ASK_AMT_5000 or less,ASK_AMT_above 1 billion,ASK_AMT_between 1 million and 50 million,ASK_AMT_between 100 million and 300 million,ASK_AMT_between 300 million and 600 million,ASK_AMT_between 50 million and 100 million,ASK_AMT_between 5000 and 1 million,ASK_AMT_between 600 million and 1 billion
0,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
34295,0,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
34296,0,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
34297,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
34298,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [103]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_df_get_dummies.values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [104]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

Compile, Train and Evaluate the Model

Attempt 1

In [132]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn1 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn1.add(tf.keras.layers.Dense(units=6, activation="relu", input_dim=47))
# Second hidden layer
#  YOUR CODE GOES HERE
nn1.add(tf.keras.layers.Dense(units=6, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn1.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 6)                 288
_________________________________________________________________
dense_13 (Dense)             (None, 6)                 42
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 7
=================================================================
Total params: 337
Trainable params: 337
Non-trainable params: 0
_________________________________________________________________

In [133]:
# Compile the model
#  YOUR CODE GOES HERE
nn1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [134]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn1.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
  1/804 [..............................] - ETA: 0s - loss: 0.9715 - accuracy: 0.5938WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0008s vs `on_train_batch_end` time: 0.0014s). Check your callbacks.
804/804 [==============================] - 0s 618us/step - loss: 0.6359 - accuracy: 0.6777
Epoch 2/100
804/804 [==============================] - 0s 589us/step - loss: 0.5705 - accuracy: 0.7262
Epoch 3/100
804/804 [==============================] - 1s 631us/step - loss: 0.5617 - accuracy: 0.7282
Epoch 4/100
804/804 [==============================] - 1s 623us/step - loss: 0.5589 - accuracy: 0.72900s - loss: 0.5581 - accuracy: 0.
Epoch 5/100
804/804 [==============================] - 0s 571us/step - loss: 0.5571 - accuracy: 0.7297
Epoch 6/100
804/804 [==============================] - 0s 575us/step - loss: 0.5554 - accuracy: 0.7301
Epoch 7/100
804/804 [==============================] - 0s 582us/step - loss: 0.5545 - accuracy: 0.7300
Epoch 8/100
804/804 [==============================] - 0s 575us/step - loss: 0.5537 - accuracy: 0.7307
Epoch 9/100
804/804 [==============================] - 0s 589us/step - loss: 0.5532 - accuracy: 0.7308
Epoch 10/100
804/804 [==============================] - 0s 596us/step - loss: 0.5526 - accuracy: 0.7317
Epoch 11/100
804/804 [==============================] - 0s 576us/step - loss: 0.5519 - accuracy: 0.7313
Epoch 12/100
804/804 [==============================] - 0s 597us/step - loss: 0.5521 - accuracy: 0.7312
Epoch 13/100
804/804 [==============================] - 0s 579us/step - loss: 0.5516 - accuracy: 0.7315
Epoch 14/100
804/804 [==============================] - 0s 580us/step - loss: 0.5510 - accuracy: 0.7307
Epoch 15/100
804/804 [==============================] - 0s 581us/step - loss: 0.5509 - accuracy: 0.7313
Epoch 16/100
804/804 [==============================] - 0s 580us/step - loss: 0.5510 - accuracy: 0.7313
Epoch 17/100
804/804 [==============================] - 0s 585us/step - loss: 0.5505 - accuracy: 0.7317
Epoch 18/100
804/804 [==============================] - 0s 576us/step - loss: 0.5500 - accuracy: 0.7317
Epoch 19/100
804/804 [==============================] - 0s 580us/step - loss: 0.5498 - accuracy: 0.7319
Epoch 20/100
804/804 [==============================] - 0s 580us/step - loss: 0.5496 - accuracy: 0.7327
Epoch 21/100
804/804 [==============================] - 0s 570us/step - loss: 0.5493 - accuracy: 0.7319
Epoch 22/100
804/804 [==============================] - 0s 586us/step - loss: 0.5494 - accuracy: 0.7317
Epoch 23/100
804/804 [==============================] - 0s 578us/step - loss: 0.5493 - accuracy: 0.7327
Epoch 24/100
804/804 [==============================] - 0s 596us/step - loss: 0.5487 - accuracy: 0.7326
Epoch 25/100
804/804 [==============================] - 0s 600us/step - loss: 0.5487 - accuracy: 0.7327
Epoch 26/100
804/804 [==============================] - 0s 578us/step - loss: 0.5487 - accuracy: 0.7316
Epoch 27/100
804/804 [==============================] - 0s 578us/step - loss: 0.5483 - accuracy: 0.7322
Epoch 28/100
804/804 [==============================] - 0s 579us/step - loss: 0.5484 - accuracy: 0.7320
Epoch 29/100
804/804 [==============================] - 0s 600us/step - loss: 0.5478 - accuracy: 0.7334
Epoch 30/100
804/804 [==============================] - 0s 575us/step - loss: 0.5479 - accuracy: 0.7327
Epoch 31/100
804/804 [==============================] - 0s 576us/step - loss: 0.5478 - accuracy: 0.7328
Epoch 32/100
804/804 [==============================] - 0s 579us/step - loss: 0.5479 - accuracy: 0.7323
Epoch 33/100
804/804 [==============================] - 0s 582us/step - loss: 0.5477 - accuracy: 0.7331
Epoch 34/100
804/804 [==============================] - 0s 592us/step - loss: 0.5477 - accuracy: 0.7325
Epoch 35/100
804/804 [==============================] - 0s 579us/step - loss: 0.5479 - accuracy: 0.7320
Epoch 36/100
804/804 [==============================] - 0s 584us/step - loss: 0.5475 - accuracy: 0.7327
Epoch 37/100
804/804 [==============================] - 0s 609us/step - loss: 0.5478 - accuracy: 0.7327
Epoch 38/100
804/804 [==============================] - 0s 577us/step - loss: 0.5472 - accuracy: 0.7326
Epoch 39/100
804/804 [==============================] - 0s 574us/step - loss: 0.5476 - accuracy: 0.7324
Epoch 40/100
804/804 [==============================] - 0s 573us/step - loss: 0.5475 - accuracy: 0.7319
Epoch 41/100
804/804 [==============================] - 0s 573us/step - loss: 0.5475 - accuracy: 0.7321
Epoch 42/100
804/804 [==============================] - 0s 590us/step - loss: 0.5472 - accuracy: 0.7326
Epoch 43/100
804/804 [==============================] - 0s 580us/step - loss: 0.5472 - accuracy: 0.7322
Epoch 44/100
804/804 [==============================] - 0s 580us/step - loss: 0.5474 - accuracy: 0.7324
Epoch 45/100
804/804 [==============================] - 0s 576us/step - loss: 0.5472 - accuracy: 0.7315
Epoch 46/100
804/804 [==============================] - 0s 580us/step - loss: 0.5473 - accuracy: 0.7329
Epoch 47/100
804/804 [==============================] - 0s 599us/step - loss: 0.5470 - accuracy: 0.7323
Epoch 48/100
804/804 [==============================] - 0s 584us/step - loss: 0.5469 - accuracy: 0.7325
Epoch 49/100
804/804 [==============================] - 0s 578us/step - loss: 0.5472 - accuracy: 0.7322
Epoch 50/100
804/804 [==============================] - 0s 580us/step - loss: 0.5469 - accuracy: 0.7324
Epoch 51/100
804/804 [==============================] - 0s 576us/step - loss: 0.5469 - accuracy: 0.7330
Epoch 52/100
804/804 [==============================] - 0s 575us/step - loss: 0.5469 - accuracy: 0.7321
Epoch 53/100
804/804 [==============================] - 0s 596us/step - loss: 0.5470 - accuracy: 0.7324
Epoch 54/100
804/804 [==============================] - 0s 574us/step - loss: 0.5469 - accuracy: 0.7324
Epoch 55/100
804/804 [==============================] - 0s 572us/step - loss: 0.5471 - accuracy: 0.7322
Epoch 56/100
804/804 [==============================] - 0s 581us/step - loss: 0.5469 - accuracy: 0.7326
Epoch 57/100
804/804 [==============================] - 0s 564us/step - loss: 0.5470 - accuracy: 0.7327
Epoch 58/100
804/804 [==============================] - 0s 576us/step - loss: 0.5468 - accuracy: 0.7334
Epoch 59/100
804/804 [==============================] - 0s 573us/step - loss: 0.5466 - accuracy: 0.7318
Epoch 60/100
804/804 [==============================] - 0s 569us/step - loss: 0.5470 - accuracy: 0.7321
Epoch 61/100
804/804 [==============================] - 0s 597us/step - loss: 0.5469 - accuracy: 0.7323
Epoch 62/100
804/804 [==============================] - 0s 574us/step - loss: 0.5469 - accuracy: 0.7328
Epoch 63/100
804/804 [==============================] - 0s 565us/step - loss: 0.5466 - accuracy: 0.7328
Epoch 64/100
804/804 [==============================] - 0s 571us/step - loss: 0.5465 - accuracy: 0.7325
Epoch 65/100
804/804 [==============================] - 0s 585us/step - loss: 0.5467 - accuracy: 0.7332
Epoch 66/100
804/804 [==============================] - 1s 740us/step - loss: 0.5466 - accuracy: 0.7324
Epoch 67/100
804/804 [==============================] - 0s 578us/step - loss: 0.5468 - accuracy: 0.7323
Epoch 68/100
804/804 [==============================] - 0s 565us/step - loss: 0.5465 - accuracy: 0.7328
Epoch 69/100
804/804 [==============================] - 0s 572us/step - loss: 0.5465 - accuracy: 0.7323
Epoch 70/100
804/804 [==============================] - 0s 571us/step - loss: 0.5467 - accuracy: 0.7323
Epoch 71/100
804/804 [==============================] - 0s 564us/step - loss: 0.5466 - accuracy: 0.7324
Epoch 72/100
804/804 [==============================] - 0s 568us/step - loss: 0.5465 - accuracy: 0.7325
Epoch 73/100
804/804 [==============================] - 0s 569us/step - loss: 0.5466 - accuracy: 0.7328
Epoch 74/100
804/804 [==============================] - 0s 595us/step - loss: 0.5467 - accuracy: 0.7329
Epoch 75/100
804/804 [==============================] - 0s 591us/step - loss: 0.5464 - accuracy: 0.7320
Epoch 76/100
804/804 [==============================] - 0s 567us/step - loss: 0.5464 - accuracy: 0.7325
Epoch 77/100

804/804 [==============================] - 0s 561us/step - loss: 0.5466 - accuracy: 0.7336
Epoch 78/100
804/804 [==============================] - 0s 568us/step - loss: 0.5464 - accuracy: 0.7325
Epoch 79/100
804/804 [==============================] - 0s 570us/step - loss: 0.5462 - accuracy: 0.7320
Epoch 80/100
804/804 [==============================] - 0s 573us/step - loss: 0.5466 - accuracy: 0.7330
Epoch 81/100
804/804 [==============================] - 0s 562us/step - loss: 0.5464 - accuracy: 0.7330
Epoch 82/100
804/804 [==============================] - 0s 620us/step - loss: 0.5465 - accuracy: 0.7322
Epoch 83/100
804/804 [==============================] - 0s 563us/step - loss: 0.5462 - accuracy: 0.7334
Epoch 84/100
804/804 [==============================] - 0s 572us/step - loss: 0.5461 - accuracy: 0.7330
Epoch 85/100
804/804 [==============================] - 0s 563us/step - loss: 0.5462 - accuracy: 0.7322
Epoch 86/100
804/804 [==============================] - 0s 570us/step - loss: 0.5465 - accuracy: 0.7322
Epoch 87/100
804/804 [==============================] - 0s 572us/step - loss: 0.5464 - accuracy: 0.7329
Epoch 88/100
804/804 [==============================] - 0s 571us/step - loss: 0.5462 - accuracy: 0.7328
Epoch 89/100
804/804 [==============================] - 0s 564us/step - loss: 0.5465 - accuracy: 0.7330
Epoch 90/100
804/804 [==============================] - 0s 566us/step - loss: 0.5463 - accuracy: 0.7325
Epoch 91/100
804/804 [==============================] - 0s 564us/step - loss: 0.5462 - accuracy: 0.7327
Epoch 92/100
804/804 [==============================] - 0s 573us/step - loss: 0.5460 - accuracy: 0.7331
Epoch 93/100
804/804 [==============================] - 0s 564us/step - loss: 0.5461 - accuracy: 0.7324
Epoch 94/100
804/804 [==============================] - 0s 568us/step - loss: 0.5460 - accuracy: 0.7333
Epoch 95/100
804/804 [==============================] - 0s 566us/step - loss: 0.5462 - accuracy: 0.7331
Epoch 96/100
804/804 [==============================] - 0s 564us/step - loss: 0.5459 - accuracy: 0.7328
Epoch 97/100
804/804 [==============================] - 0s 568us/step - loss: 0.5460 - accuracy: 0.7335
Epoch 98/100
804/804 [==============================] - 0s 566us/step - loss: 0.5460 - accuracy: 0.7327
Epoch 99/100
804/804 [==============================] - 0s 566us/step - loss: 0.5457 - accuracy: 0.7331
Epoch 100/100
804/804 [==============================] - 0s 565us/step - loss: 0.5459 - accuracy: 0.7325

In [136]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn1.evaluate(X_train_scaled,y_train,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

804/804 - 1s - loss: 0.5449 - accuracy: 0.7339
Loss: 0.5448875427246094, Accuracy: 0.7338672280311584

Attempt 2

In [137]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn2 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=10, activation="relu", input_dim=47))
# Second hidden layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=10, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn2.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_15 (Dense)             (None, 10)                480
_________________________________________________________________
dense_16 (Dense)             (None, 10)                110
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 11
=================================================================
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________

In [138]:
# Compile the model
#  YOUR CODE GOES HERE
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [139]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn2.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 1s 678us/step - loss: 0.5941 - accuracy: 0.7082
Epoch 2/200
804/804 [==============================] - 0s 578us/step - loss: 0.5623 - accuracy: 0.7267
Epoch 3/200
804/804 [==============================] - 0s 561us/step - loss: 0.5573 - accuracy: 0.7306
Epoch 4/200
804/804 [==============================] - 1s 704us/step - loss: 0.5550 - accuracy: 0.7309
Epoch 5/200
804/804 [==============================] - 0s 545us/step - loss: 0.5537 - accuracy: 0.7322
Epoch 6/200
804/804 [==============================] - 0s 534us/step - loss: 0.5528 - accuracy: 0.7330
Epoch 7/200
804/804 [==============================] - 0s 553us/step - loss: 0.5517 - accuracy: 0.7318
Epoch 8/200
804/804 [==============================] - 0s 564us/step - loss: 0.5511 - accuracy: 0.7319
Epoch 9/200
804/804 [==============================] - 0s 559us/step - loss: 0.5499 - accuracy: 0.7331
Epoch 10/200
804/804 [==============================] - 0s 540us/step - loss: 0.5494 - accuracy: 0.7334
Epoch 11/200
804/804 [==============================] - 0s 563us/step - loss: 0.5492 - accuracy: 0.7332
Epoch 12/200
804/804 [==============================] - 0s 546us/step - loss: 0.5488 - accuracy: 0.7318
Epoch 13/200
804/804 [==============================] - 0s 549us/step - loss: 0.5486 - accuracy: 0.7332
Epoch 14/200
804/804 [==============================] - 0s 547us/step - loss: 0.5480 - accuracy: 0.7329
Epoch 15/200
804/804 [==============================] - 0s 546us/step - loss: 0.5473 - accuracy: 0.7329
Epoch 16/200
804/804 [==============================] - 0s 578us/step - loss: 0.5478 - accuracy: 0.7338
Epoch 17/200
804/804 [==============================] - 0s 543us/step - loss: 0.5473 - accuracy: 0.7329
Epoch 18/200
804/804 [==============================] - 0s 571us/step - loss: 0.5468 - accuracy: 0.7330
Epoch 19/200
804/804 [==============================] - 0s 537us/step - loss: 0.5466 - accuracy: 0.7334
Epoch 20/200
804/804 [==============================] - 0s 553us/step - loss: 0.5464 - accuracy: 0.7330
Epoch 21/200
804/804 [==============================] - 0s 544us/step - loss: 0.5462 - accuracy: 0.7320
Epoch 22/200
804/804 [==============================] - 0s 545us/step - loss: 0.5462 - accuracy: 0.7329
Epoch 23/200
804/804 [==============================] - 0s 560us/step - loss: 0.5460 - accuracy: 0.7333
Epoch 24/200
804/804 [==============================] - 0s 544us/step - loss: 0.5459 - accuracy: 0.7347
Epoch 25/200
804/804 [==============================] - 0s 555us/step - loss: 0.5459 - accuracy: 0.7343
Epoch 26/200
804/804 [==============================] - 0s 543us/step - loss: 0.5457 - accuracy: 0.7334
Epoch 27/200
804/804 [==============================] - 0s 533us/step - loss: 0.5452 - accuracy: 0.7336
Epoch 28/200
804/804 [==============================] - 0s 536us/step - loss: 0.5457 - accuracy: 0.7337
Epoch 29/200
804/804 [==============================] - 0s 550us/step - loss: 0.5454 - accuracy: 0.7337
Epoch 30/200
804/804 [==============================] - 0s 546us/step - loss: 0.5455 - accuracy: 0.7335
Epoch 31/200
804/804 [==============================] - 0s 534us/step - loss: 0.5450 - accuracy: 0.7340
Epoch 32/200
804/804 [==============================] - 0s 548us/step - loss: 0.5450 - accuracy: 0.7344
Epoch 33/200
804/804 [==============================] - 0s 544us/step - loss: 0.5449 - accuracy: 0.7339
Epoch 34/200
804/804 [==============================] - 0s 546us/step - loss: 0.5449 - accuracy: 0.7345
Epoch 35/200
804/804 [==============================] - 0s 586us/step - loss: 0.5446 - accuracy: 0.7348
Epoch 36/200
804/804 [==============================] - 0s 559us/step - loss: 0.5443 - accuracy: 0.7349
Epoch 37/200
804/804 [==============================] - 0s 544us/step - loss: 0.5442 - accuracy: 0.7346
Epoch 38/200
804/804 [==============================] - 0s 544us/step - loss: 0.5443 - accuracy: 0.7341
Epoch 39/200
804/804 [==============================] - 0s 562us/step - loss: 0.5441 - accuracy: 0.7351
Epoch 40/200
804/804 [==============================] - 0s 537us/step - loss: 0.5441 - accuracy: 0.7355
Epoch 41/200
804/804 [==============================] - 0s 542us/step - loss: 0.5440 - accuracy: 0.7355
Epoch 42/200
804/804 [==============================] - 0s 559us/step - loss: 0.5438 - accuracy: 0.7349
Epoch 43/200
804/804 [==============================] - 0s 543us/step - loss: 0.5440 - accuracy: 0.7355
Epoch 44/200
804/804 [==============================] - 0s 554us/step - loss: 0.5436 - accuracy: 0.7346
Epoch 45/200
804/804 [==============================] - 0s 558us/step - loss: 0.5434 - accuracy: 0.7354
Epoch 46/200
804/804 [==============================] - 0s 555us/step - loss: 0.5435 - accuracy: 0.7345
Epoch 47/200
804/804 [==============================] - 0s 574us/step - loss: 0.5436 - accuracy: 0.73360s - loss: 0.5508 -
Epoch 48/200
804/804 [==============================] - 0s 542us/step - loss: 0.5436 - accuracy: 0.7347
Epoch 49/200
804/804 [==============================] - 0s 542us/step - loss: 0.5431 - accuracy: 0.7348
Epoch 50/200
804/804 [==============================] - 0s 556us/step - loss: 0.5437 - accuracy: 0.7346
Epoch 51/200
804/804 [==============================] - 0s 536us/step - loss: 0.5432 - accuracy: 0.7345
Epoch 52/200
804/804 [==============================] - 0s 569us/step - loss: 0.5433 - accuracy: 0.7356
Epoch 53/200
804/804 [==============================] - 0s 554us/step - loss: 0.5432 - accuracy: 0.7357
Epoch 54/200
804/804 [==============================] - 0s 536us/step - loss: 0.5430 - accuracy: 0.7343
Epoch 55/200
804/804 [==============================] - 0s 560us/step - loss: 0.5429 - accuracy: 0.7354
Epoch 56/200
804/804 [==============================] - 0s 526us/step - loss: 0.5429 - accuracy: 0.7357
Epoch 57/200
804/804 [==============================] - 0s 554us/step - loss: 0.5429 - accuracy: 0.7369
Epoch 58/200
804/804 [==============================] - 0s 554us/step - loss: 0.5430 - accuracy: 0.73460s - loss: 0.5459 - accuracy:
Epoch 59/200
804/804 [==============================] - 0s 574us/step - loss: 0.5426 - accuracy: 0.7350
Epoch 60/200
804/804 [==============================] - 0s 539us/step - loss: 0.5426 - accuracy: 0.7354
Epoch 61/200
804/804 [==============================] - 0s 539us/step - loss: 0.5432 - accuracy: 0.7349
Epoch 62/200
804/804 [==============================] - 1s 667us/step - loss: 0.5423 - accuracy: 0.7364
Epoch 63/200
804/804 [==============================] - 0s 565us/step - loss: 0.5427 - accuracy: 0.7352
Epoch 64/200
804/804 [==============================] - 0s 530us/step - loss: 0.5427 - accuracy: 0.7348
Epoch 65/200
804/804 [==============================] - 0s 616us/step - loss: 0.5427 - accuracy: 0.7348
Epoch 66/200
804/804 [==============================] - 0s 555us/step - loss: 0.5422 - accuracy: 0.7362
Epoch 67/200
804/804 [==============================] - 0s 539us/step - loss: 0.5425 - accuracy: 0.7355
Epoch 68/200
804/804 [==============================] - 0s 597us/step - loss: 0.5423 - accuracy: 0.7363
Epoch 69/200
804/804 [==============================] - 0s 591us/step - loss: 0.5424 - accuracy: 0.7363
Epoch 70/200
804/804 [==============================] - 0s 561us/step - loss: 0.5424 - accuracy: 0.7364
Epoch 71/200
804/804 [==============================] - 0s 570us/step - loss: 0.5426 - accuracy: 0.7348
Epoch 72/200
804/804 [==============================] - 0s 557us/step - loss: 0.5420 - accuracy: 0.7365
Epoch 73/200
804/804 [==============================] - 0s 548us/step - loss: 0.5422 - accuracy: 0.7357
Epoch 74/200
804/804 [==============================] - 0s 539us/step - loss: 0.5425 - accuracy: 0.7356
Epoch 75/200
804/804 [==============================] - 0s 541us/step - loss: 0.5421 - accuracy: 0.7357
Epoch 76/200
804/804 [==============================] - 0s 533us/step - loss: 0.5421 - accuracy: 0.7371
Epoch 77/200
804/804 [==============================] - 1s 633us/step - loss: 0.5426 - accuracy: 0.7359
Epoch 78/200
804/804 [==============================] - 0s 527us/step - loss: 0.5421 - accuracy: 0.7367
Epoch 79/200

804/804 [==============================] - 0s 592us/step - loss: 0.5419 - accuracy: 0.7358
Epoch 80/200
804/804 [==============================] - 0s 545us/step - loss: 0.5422 - accuracy: 0.7356
Epoch 81/200
804/804 [==============================] - 0s 537us/step - loss: 0.5423 - accuracy: 0.7368
Epoch 82/200
804/804 [==============================] - 0s 541us/step - loss: 0.5420 - accuracy: 0.7362
Epoch 83/200
804/804 [==============================] - 0s 529us/step - loss: 0.5419 - accuracy: 0.7358
Epoch 84/200
804/804 [==============================] - 0s 536us/step - loss: 0.5419 - accuracy: 0.7368
Epoch 85/200
804/804 [==============================] - 0s 544us/step - loss: 0.5417 - accuracy: 0.7367
Epoch 86/200
804/804 [==============================] - 0s 535us/step - loss: 0.5420 - accuracy: 0.7368
Epoch 87/200
804/804 [==============================] - 0s 549us/step - loss: 0.5417 - accuracy: 0.7360
Epoch 88/200
804/804 [==============================] - 0s 545us/step - loss: 0.5419 - accuracy: 0.7368
Epoch 89/200
804/804 [==============================] - 0s 533us/step - loss: 0.5417 - accuracy: 0.7371
Epoch 90/200
804/804 [==============================] - 0s 544us/step - loss: 0.5418 - accuracy: 0.7358
Epoch 91/200
804/804 [==============================] - 0s 539us/step - loss: 0.5416 - accuracy: 0.7364
Epoch 92/200
804/804 [==============================] - 0s 537us/step - loss: 0.5420 - accuracy: 0.7365
Epoch 93/200
804/804 [==============================] - 0s 529us/step - loss: 0.5416 - accuracy: 0.7373
Epoch 94/200
804/804 [==============================] - 0s 604us/step - loss: 0.5417 - accuracy: 0.7364
Epoch 95/200
804/804 [==============================] - 0s 523us/step - loss: 0.5416 - accuracy: 0.7371
Epoch 96/200
804/804 [==============================] - 0s 530us/step - loss: 0.5415 - accuracy: 0.7372
Epoch 97/200
804/804 [==============================] - 0s 538us/step - loss: 0.5415 - accuracy: 0.7365
Epoch 98/200
804/804 [==============================] - 0s 535us/step - loss: 0.5415 - accuracy: 0.7366
Epoch 99/200
804/804 [==============================] - 0s 532us/step - loss: 0.5415 - accuracy: 0.7365
Epoch 100/200
804/804 [==============================] - 0s 536us/step - loss: 0.5413 - accuracy: 0.7374
Epoch 101/200
804/804 [==============================] - 0s 533us/step - loss: 0.5415 - accuracy: 0.7366
Epoch 102/200
804/804 [==============================] - 0s 526us/step - loss: 0.5414 - accuracy: 0.7361
Epoch 103/200
804/804 [==============================] - 0s 530us/step - loss: 0.5414 - accuracy: 0.7368
Epoch 104/200
804/804 [==============================] - 0s 530us/step - loss: 0.5414 - accuracy: 0.7361
Epoch 105/200
804/804 [==============================] - 0s 548us/step - loss: 0.5409 - accuracy: 0.7369
Epoch 106/200
804/804 [==============================] - 0s 550us/step - loss: 0.5411 - accuracy: 0.7374
Epoch 107/200
804/804 [==============================] - 0s 548us/step - loss: 0.5414 - accuracy: 0.7363
Epoch 108/200
804/804 [==============================] - 0s 535us/step - loss: 0.5413 - accuracy: 0.7368
Epoch 109/200
804/804 [==============================] - 0s 530us/step - loss: 0.5414 - accuracy: 0.7366
Epoch 110/200
804/804 [==============================] - 0s 541us/step - loss: 0.5412 - accuracy: 0.7368
Epoch 111/200
804/804 [==============================] - 0s 540us/step - loss: 0.5415 - accuracy: 0.7362
Epoch 112/200
804/804 [==============================] - 0s 545us/step - loss: 0.5411 - accuracy: 0.7369
Epoch 113/200
804/804 [==============================] - 0s 557us/step - loss: 0.5409 - accuracy: 0.7381
Epoch 114/200
804/804 [==============================] - 0s 555us/step - loss: 0.5413 - accuracy: 0.7366
Epoch 115/200
804/804 [==============================] - 1s 943us/step - loss: 0.5414 - accuracy: 0.7373
Epoch 116/200
804/804 [==============================] - 1s 624us/step - loss: 0.5410 - accuracy: 0.7365
Epoch 117/200
804/804 [==============================] - 0s 562us/step - loss: 0.5411 - accuracy: 0.7371
Epoch 118/200
804/804 [==============================] - 0s 551us/step - loss: 0.5414 - accuracy: 0.7372
Epoch 119/200
804/804 [==============================] - 0s 539us/step - loss: 0.5407 - accuracy: 0.7379
Epoch 120/200
804/804 [==============================] - 0s 538us/step - loss: 0.5415 - accuracy: 0.7366
Epoch 121/200
804/804 [==============================] - 0s 545us/step - loss: 0.5410 - accuracy: 0.7376
Epoch 122/200
804/804 [==============================] - 0s 543us/step - loss: 0.5410 - accuracy: 0.7367
Epoch 123/200
804/804 [==============================] - 0s 534us/step - loss: 0.5408 - accuracy: 0.7380
Epoch 124/200
804/804 [==============================] - 0s 537us/step - loss: 0.5405 - accuracy: 0.7374
Epoch 125/200
804/804 [==============================] - 0s 550us/step - loss: 0.5410 - accuracy: 0.7370
Epoch 126/200
804/804 [==============================] - 0s 547us/step - loss: 0.5411 - accuracy: 0.7370
Epoch 127/200
804/804 [==============================] - 0s 536us/step - loss: 0.5410 - accuracy: 0.7373
Epoch 128/200
804/804 [==============================] - 0s 538us/step - loss: 0.5408 - accuracy: 0.7366
Epoch 129/200
804/804 [==============================] - 0s 534us/step - loss: 0.5411 - accuracy: 0.7363
Epoch 130/200
804/804 [==============================] - 0s 552us/step - loss: 0.5409 - accuracy: 0.7369
Epoch 131/200
804/804 [==============================] - 0s 539us/step - loss: 0.5408 - accuracy: 0.7372
Epoch 132/200
804/804 [==============================] - 0s 534us/step - loss: 0.5410 - accuracy: 0.7369
Epoch 133/200
804/804 [==============================] - 0s 544us/step - loss: 0.5409 - accuracy: 0.7371
Epoch 134/200
804/804 [==============================] - 0s 534us/step - loss: 0.5410 - accuracy: 0.7363
Epoch 135/200
804/804 [==============================] - 0s 543us/step - loss: 0.5406 - accuracy: 0.7366
Epoch 136/200
804/804 [==============================] - 0s 561us/step - loss: 0.5408 - accuracy: 0.7374
Epoch 137/200
804/804 [==============================] - 0s 540us/step - loss: 0.5408 - accuracy: 0.7374
Epoch 138/200
804/804 [==============================] - 0s 546us/step - loss: 0.5406 - accuracy: 0.7373
Epoch 139/200
804/804 [==============================] - 0s 533us/step - loss: 0.5407 - accuracy: 0.7380
Epoch 140/200
804/804 [==============================] - 0s 537us/step - loss: 0.5407 - accuracy: 0.7367
Epoch 141/200
804/804 [==============================] - 0s 553us/step - loss: 0.5403 - accuracy: 0.73730s - loss: 0.5469 - ac
Epoch 142/200
804/804 [==============================] - 0s 553us/step - loss: 0.5412 - accuracy: 0.7367
Epoch 143/200
804/804 [==============================] - 0s 527us/step - loss: 0.5408 - accuracy: 0.7376
Epoch 144/200
804/804 [==============================] - 0s 532us/step - loss: 0.5406 - accuracy: 0.7372
Epoch 145/200
804/804 [==============================] - 0s 614us/step - loss: 0.5404 - accuracy: 0.7385
Epoch 146/200
804/804 [==============================] - 0s 554us/step - loss: 0.5405 - accuracy: 0.7374
Epoch 147/200
804/804 [==============================] - 0s 524us/step - loss: 0.5406 - accuracy: 0.7373
Epoch 148/200
804/804 [==============================] - 0s 552us/step - loss: 0.5402 - accuracy: 0.7375
Epoch 149/200
804/804 [==============================] - 0s 533us/step - loss: 0.5405 - accuracy: 0.7375
Epoch 150/200
804/804 [==============================] - 0s 537us/step - loss: 0.5410 - accuracy: 0.7372
Epoch 151/200
804/804 [==============================] - 0s 528us/step - loss: 0.5403 - accuracy: 0.7378
Epoch 152/200
804/804 [==============================] - 0s 536us/step - loss: 0.5403 - accuracy: 0.7371
Epoch 153/200
804/804 [==============================] - 0s 538us/step - loss: 0.5406 - accuracy: 0.7378
Epoch 154/200
804/804 [==============================] - 0s 531us/step - loss: 0.5405 - accuracy: 0.7372
Epoch 155/200
804/804 [==============================] - 0s 551us/step - loss: 0.5404 - accuracy: 0.7380
Epoch 156/200
804/804 [==============================] - 0s 520us/step - loss: 0.5404 - accuracy: 0.7365
Epoch 157/200

804/804 [==============================] - 0s 531us/step - loss: 0.5407 - accuracy: 0.7357
Epoch 158/200
804/804 [==============================] - 0s 537us/step - loss: 0.5400 - accuracy: 0.7374
Epoch 159/200
804/804 [==============================] - 0s 543us/step - loss: 0.5403 - accuracy: 0.7374
Epoch 160/200
804/804 [==============================] - 0s 539us/step - loss: 0.5404 - accuracy: 0.7376
Epoch 161/200
804/804 [==============================] - 0s 551us/step - loss: 0.5406 - accuracy: 0.7372
Epoch 162/200
804/804 [==============================] - 0s 551us/step - loss: 0.5403 - accuracy: 0.7373
Epoch 163/200
804/804 [==============================] - 0s 533us/step - loss: 0.5405 - accuracy: 0.7368
Epoch 164/200
804/804 [==============================] - 0s 527us/step - loss: 0.5404 - accuracy: 0.7361
Epoch 165/200
804/804 [==============================] - 0s 529us/step - loss: 0.5406 - accuracy: 0.7372
Epoch 166/200
804/804 [==============================] - 1s 643us/step - loss: 0.5405 - accuracy: 0.7377
Epoch 167/200
804/804 [==============================] - 0s 575us/step - loss: 0.5403 - accuracy: 0.7375
Epoch 168/200
804/804 [==============================] - 1s 637us/step - loss: 0.5403 - accuracy: 0.7376
Epoch 169/200
804/804 [==============================] - 0s 533us/step - loss: 0.5402 - accuracy: 0.7375
Epoch 170/200
804/804 [==============================] - 0s 532us/step - loss: 0.5406 - accuracy: 0.7371
Epoch 171/200
804/804 [==============================] - 0s 551us/step - loss: 0.5403 - accuracy: 0.7381
Epoch 172/200
804/804 [==============================] - 0s 522us/step - loss: 0.5405 - accuracy: 0.7370
Epoch 173/200
804/804 [==============================] - 0s 531us/step - loss: 0.5404 - accuracy: 0.7378
Epoch 174/200
804/804 [==============================] - 0s 534us/step - loss: 0.5403 - accuracy: 0.7374
Epoch 175/200
804/804 [==============================] - 0s 542us/step - loss: 0.5402 - accuracy: 0.7368
Epoch 176/200
804/804 [==============================] - 0s 518us/step - loss: 0.5403 - accuracy: 0.7368
Epoch 177/200
804/804 [==============================] - 0s 527us/step - loss: 0.5404 - accuracy: 0.7382
Epoch 178/200
804/804 [==============================] - 0s 621us/step - loss: 0.5404 - accuracy: 0.7369
Epoch 179/200
804/804 [==============================] - 0s 602us/step - loss: 0.5402 - accuracy: 0.7386
Epoch 180/200
804/804 [==============================] - 0s 575us/step - loss: 0.5401 - accuracy: 0.7369
Epoch 181/200
804/804 [==============================] - 1s 644us/step - loss: 0.5402 - accuracy: 0.7371
Epoch 182/200
804/804 [==============================] - 1s 675us/step - loss: 0.5401 - accuracy: 0.7372
Epoch 183/200
804/804 [==============================] - 0s 576us/step - loss: 0.5404 - accuracy: 0.7371
Epoch 184/200
804/804 [==============================] - 0s 567us/step - loss: 0.5397 - accuracy: 0.7374
Epoch 185/200
804/804 [==============================] - 0s 615us/step - loss: 0.5402 - accuracy: 0.7374
Epoch 186/200
804/804 [==============================] - 0s 592us/step - loss: 0.5402 - accuracy: 0.7372
Epoch 187/200
804/804 [==============================] - 0s 578us/step - loss: 0.5401 - accuracy: 0.7370
Epoch 188/200
804/804 [==============================] - 0s 543us/step - loss: 0.5401 - accuracy: 0.7376
Epoch 189/200
804/804 [==============================] - 0s 622us/step - loss: 0.5401 - accuracy: 0.7368
Epoch 190/200
804/804 [==============================] - 0s 547us/step - loss: 0.5400 - accuracy: 0.7379
Epoch 191/200
804/804 [==============================] - 0s 546us/step - loss: 0.5400 - accuracy: 0.7371
Epoch 192/200
804/804 [==============================] - 0s 586us/step - loss: 0.5399 - accuracy: 0.7380
Epoch 193/200
804/804 [==============================] - 0s 544us/step - loss: 0.5400 - accuracy: 0.7371
Epoch 194/200
804/804 [==============================] - 0s 554us/step - loss: 0.5402 - accuracy: 0.7373
Epoch 195/200
804/804 [==============================] - 0s 535us/step - loss: 0.5400 - accuracy: 0.7381
Epoch 196/200
804/804 [==============================] - 0s 535us/step - loss: 0.5399 - accuracy: 0.7377
Epoch 197/200
804/804 [==============================] - 0s 537us/step - loss: 0.5402 - accuracy: 0.7379
Epoch 198/200
804/804 [==============================] - 0s 525us/step - loss: 0.5399 - accuracy: 0.7386
Epoch 199/200
804/804 [==============================] - 0s 530us/step - loss: 0.5399 - accuracy: 0.7375
Epoch 200/200
804/804 [==============================] - 0s 536us/step - loss: 0.5399 - accuracy: 0.7369

In [140]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_train_scaled,y_train,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

WARNING:tensorflow:Callbacks method `on_test_batch_end` is slow compared to the batch time (batch time: 0.0000s vs `on_test_batch_end` time: 0.0010s). Check your callbacks.
804/804 - 0s - loss: 0.5375 - accuracy: 0.7392
Loss: 0.5374922156333923, Accuracy: 0.7391541004180908

Attempt 3

In [141]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn3 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn3.add(tf.keras.layers.Dense(units=12, activation="relu", input_dim=47))
# Second hidden layer
#  YOUR CODE GOES HERE
nn3.add(tf.keras.layers.Dense(units=12, activation="relu"))
nn3.add(tf.keras.layers.Dense(units=12, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn3.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_18 (Dense)             (None, 12)                576
_________________________________________________________________
dense_19 (Dense)             (None, 12)                156
_________________________________________________________________
dense_20 (Dense)             (None, 12)                156
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 13
=================================================================
Total params: 901
Trainable params: 901
Non-trainable params: 0
_________________________________________________________________

In [142]:
# Compile the model
#  YOUR CODE GOES HERE
nn3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [143]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn3.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 1s 628us/step - loss: 0.5924 - accuracy: 0.7067
Epoch 2/200
804/804 [==============================] - 0s 582us/step - loss: 0.5600 - accuracy: 0.7288
Epoch 3/200
804/804 [==============================] - 0s 580us/step - loss: 0.5559 - accuracy: 0.7305
Epoch 4/200
804/804 [==============================] - 0s 581us/step - loss: 0.5538 - accuracy: 0.7322
Epoch 5/200
804/804 [==============================] - 0s 577us/step - loss: 0.5515 - accuracy: 0.7329
Epoch 6/200
804/804 [==============================] - 0s 592us/step - loss: 0.5509 - accuracy: 0.7311
Epoch 7/200
804/804 [==============================] - 0s 600us/step - loss: 0.5496 - accuracy: 0.7314
Epoch 8/200
804/804 [==============================] - 0s 578us/step - loss: 0.5488 - accuracy: 0.7325
Epoch 9/200
804/804 [==============================] - 0s 578us/step - loss: 0.5481 - accuracy: 0.7330
Epoch 10/200
804/804 [==============================] - 0s 580us/step - loss: 0.5476 - accuracy: 0.7320
Epoch 11/200
804/804 [==============================] - 0s 579us/step - loss: 0.5473 - accuracy: 0.7325
Epoch 12/200
804/804 [==============================] - 0s 574us/step - loss: 0.5462 - accuracy: 0.7336
Epoch 13/200
804/804 [==============================] - 0s 591us/step - loss: 0.5461 - accuracy: 0.7337
Epoch 14/200
804/804 [==============================] - 0s 572us/step - loss: 0.5457 - accuracy: 0.7332
Epoch 15/200
804/804 [==============================] - 0s 586us/step - loss: 0.5452 - accuracy: 0.7342
Epoch 16/200
804/804 [==============================] - 0s 570us/step - loss: 0.5450 - accuracy: 0.7330
Epoch 17/200
804/804 [==============================] - 0s 570us/step - loss: 0.5449 - accuracy: 0.7337
Epoch 18/200
804/804 [==============================] - 0s 589us/step - loss: 0.5446 - accuracy: 0.7339
Epoch 19/200
804/804 [==============================] - 0s 577us/step - loss: 0.5446 - accuracy: 0.7331
Epoch 20/200
804/804 [==============================] - 0s 593us/step - loss: 0.5445 - accuracy: 0.7339
Epoch 21/200
804/804 [==============================] - 0s 574us/step - loss: 0.5442 - accuracy: 0.7345
Epoch 22/200
804/804 [==============================] - 0s 584us/step - loss: 0.5437 - accuracy: 0.7349
Epoch 23/200
804/804 [==============================] - 0s 572us/step - loss: 0.5438 - accuracy: 0.7352
Epoch 24/200
804/804 [==============================] - 0s 603us/step - loss: 0.5435 - accuracy: 0.7339
Epoch 25/200
804/804 [==============================] - 0s 580us/step - loss: 0.5431 - accuracy: 0.7356
Epoch 26/200
804/804 [==============================] - 0s 604us/step - loss: 0.5432 - accuracy: 0.7354
Epoch 27/200
804/804 [==============================] - 0s 577us/step - loss: 0.5430 - accuracy: 0.7351
Epoch 28/200
804/804 [==============================] - 0s 587us/step - loss: 0.5429 - accuracy: 0.7368
Epoch 29/200
804/804 [==============================] - 0s 583us/step - loss: 0.5428 - accuracy: 0.7362
Epoch 30/200
804/804 [==============================] - 0s 595us/step - loss: 0.5424 - accuracy: 0.7366
Epoch 31/200
804/804 [==============================] - 0s 596us/step - loss: 0.5430 - accuracy: 0.7369
Epoch 32/200
804/804 [==============================] - 0s 572us/step - loss: 0.5422 - accuracy: 0.7358
Epoch 33/200
804/804 [==============================] - 0s 590us/step - loss: 0.5424 - accuracy: 0.7383
Epoch 34/200
804/804 [==============================] - 0s 586us/step - loss: 0.5418 - accuracy: 0.7357
Epoch 35/200
804/804 [==============================] - 0s 587us/step - loss: 0.5419 - accuracy: 0.7363
Epoch 36/200
804/804 [==============================] - 0s 574us/step - loss: 0.5422 - accuracy: 0.7364
Epoch 37/200
804/804 [==============================] - 0s 593us/step - loss: 0.5420 - accuracy: 0.7377
Epoch 38/200
804/804 [==============================] - 0s 577us/step - loss: 0.5416 - accuracy: 0.7375
Epoch 39/200
804/804 [==============================] - 0s 608us/step - loss: 0.5417 - accuracy: 0.7369
Epoch 40/200
804/804 [==============================] - 1s 677us/step - loss: 0.5419 - accuracy: 0.7371
Epoch 41/200
804/804 [==============================] - 0s 584us/step - loss: 0.5415 - accuracy: 0.7358
Epoch 42/200
804/804 [==============================] - 0s 588us/step - loss: 0.5417 - accuracy: 0.7369
Epoch 43/200
804/804 [==============================] - 0s 600us/step - loss: 0.5412 - accuracy: 0.7362
Epoch 44/200
804/804 [==============================] - 0s 577us/step - loss: 0.5413 - accuracy: 0.7374
Epoch 45/200
804/804 [==============================] - 0s 588us/step - loss: 0.5412 - accuracy: 0.7363
Epoch 46/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7378
Epoch 47/200
804/804 [==============================] - 0s 608us/step - loss: 0.5409 - accuracy: 0.7367
Epoch 48/200
804/804 [==============================] - 0s 585us/step - loss: 0.5408 - accuracy: 0.7375
Epoch 49/200
804/804 [==============================] - 0s 575us/step - loss: 0.5408 - accuracy: 0.7373
Epoch 50/200
804/804 [==============================] - 0s 575us/step - loss: 0.5411 - accuracy: 0.7371
Epoch 51/200
804/804 [==============================] - 0s 591us/step - loss: 0.5409 - accuracy: 0.7372
Epoch 52/200
804/804 [==============================] - 0s 570us/step - loss: 0.5407 - accuracy: 0.7384
Epoch 53/200
804/804 [==============================] - 0s 576us/step - loss: 0.5406 - accuracy: 0.7375
Epoch 54/200
804/804 [==============================] - 0s 576us/step - loss: 0.5408 - accuracy: 0.7381
Epoch 55/200
804/804 [==============================] - 0s 578us/step - loss: 0.5405 - accuracy: 0.7369
Epoch 56/200
804/804 [==============================] - 0s 576us/step - loss: 0.5405 - accuracy: 0.7370
Epoch 57/200
804/804 [==============================] - 0s 582us/step - loss: 0.5406 - accuracy: 0.7372
Epoch 58/200
804/804 [==============================] - 0s 568us/step - loss: 0.5403 - accuracy: 0.7380
Epoch 59/200
804/804 [==============================] - 0s 576us/step - loss: 0.5401 - accuracy: 0.7370
Epoch 60/200
804/804 [==============================] - 0s 565us/step - loss: 0.5403 - accuracy: 0.7382
Epoch 61/200
804/804 [==============================] - 0s 562us/step - loss: 0.5405 - accuracy: 0.7369
Epoch 62/200
804/804 [==============================] - 0s 602us/step - loss: 0.5401 - accuracy: 0.7374
Epoch 63/200
804/804 [==============================] - 0s 570us/step - loss: 0.5402 - accuracy: 0.7375
Epoch 64/200
804/804 [==============================] - 0s 604us/step - loss: 0.5399 - accuracy: 0.7384
Epoch 65/200
804/804 [==============================] - 0s 566us/step - loss: 0.5399 - accuracy: 0.7389
Epoch 66/200
804/804 [==============================] - 0s 565us/step - loss: 0.5395 - accuracy: 0.7390
Epoch 67/200
804/804 [==============================] - 0s 574us/step - loss: 0.5400 - accuracy: 0.7379
Epoch 68/200
804/804 [==============================] - 0s 586us/step - loss: 0.5396 - accuracy: 0.7379
Epoch 69/200
804/804 [==============================] - 0s 565us/step - loss: 0.5396 - accuracy: 0.7379
Epoch 70/200
804/804 [==============================] - 0s 582us/step - loss: 0.5396 - accuracy: 0.7379
Epoch 71/200
804/804 [==============================] - 0s 566us/step - loss: 0.5392 - accuracy: 0.7370
Epoch 72/200
804/804 [==============================] - 0s 563us/step - loss: 0.5395 - accuracy: 0.7379
Epoch 73/200
804/804 [==============================] - 0s 569us/step - loss: 0.5396 - accuracy: 0.7393
Epoch 74/200
804/804 [==============================] - 0s 570us/step - loss: 0.5396 - accuracy: 0.7386
Epoch 75/200
804/804 [==============================] - 0s 621us/step - loss: 0.5393 - accuracy: 0.7393
Epoch 76/200
804/804 [==============================] - 0s 570us/step - loss: 0.5392 - accuracy: 0.7379
Epoch 77/200
804/804 [==============================] - 0s 583us/step - loss: 0.5393 - accuracy: 0.7393
Epoch 78/200
804/804 [==============================] - 0s 564us/step - loss: 0.5394 - accuracy: 0.7390
Epoch 79/200

804/804 [==============================] - 0s 577us/step - loss: 0.5391 - accuracy: 0.7393
Epoch 80/200
804/804 [==============================] - 0s 562us/step - loss: 0.5393 - accuracy: 0.7377
Epoch 81/200
804/804 [==============================] - 0s 591us/step - loss: 0.5393 - accuracy: 0.7382
Epoch 82/200
804/804 [==============================] - 0s 563us/step - loss: 0.5389 - accuracy: 0.7385
Epoch 83/200
804/804 [==============================] - 0s 567us/step - loss: 0.5392 - accuracy: 0.7390
Epoch 84/200
804/804 [==============================] - 0s 587us/step - loss: 0.5390 - accuracy: 0.7391
Epoch 85/200
804/804 [==============================] - 0s 569us/step - loss: 0.5388 - accuracy: 0.7396
Epoch 86/200
804/804 [==============================] - 0s 583us/step - loss: 0.5386 - accuracy: 0.7396
Epoch 87/200
804/804 [==============================] - 0s 557us/step - loss: 0.5389 - accuracy: 0.7392
Epoch 88/200
804/804 [==============================] - 0s 583us/step - loss: 0.5386 - accuracy: 0.7383
Epoch 89/200
804/804 [==============================] - 0s 563us/step - loss: 0.5386 - accuracy: 0.7395
Epoch 90/200
804/804 [==============================] - 0s 584us/step - loss: 0.5385 - accuracy: 0.7383
Epoch 91/200
804/804 [==============================] - 0s 600us/step - loss: 0.5386 - accuracy: 0.7392
Epoch 92/200
804/804 [==============================] - 0s 589us/step - loss: 0.5382 - accuracy: 0.7397
Epoch 93/200
804/804 [==============================] - 0s 567us/step - loss: 0.5386 - accuracy: 0.7386
Epoch 94/200
804/804 [==============================] - 0s 564us/step - loss: 0.5388 - accuracy: 0.7397
Epoch 95/200
804/804 [==============================] - 0s 584us/step - loss: 0.5378 - accuracy: 0.7395
Epoch 96/200
804/804 [==============================] - 0s 564us/step - loss: 0.5383 - accuracy: 0.7386
Epoch 97/200
804/804 [==============================] - 0s 564us/step - loss: 0.5382 - accuracy: 0.7383
Epoch 98/200
804/804 [==============================] - 0s 555us/step - loss: 0.5381 - accuracy: 0.7395
Epoch 99/200
804/804 [==============================] - 0s 584us/step - loss: 0.5378 - accuracy: 0.7388
Epoch 100/200
804/804 [==============================] - 0s 574us/step - loss: 0.5382 - accuracy: 0.7394
Epoch 101/200
804/804 [==============================] - 0s 588us/step - loss: 0.5379 - accuracy: 0.7396
Epoch 102/200
804/804 [==============================] - 0s 569us/step - loss: 0.5378 - accuracy: 0.7400
Epoch 103/200
804/804 [==============================] - 0s 591us/step - loss: 0.5382 - accuracy: 0.7385
Epoch 104/200
804/804 [==============================] - 0s 592us/step - loss: 0.5377 - accuracy: 0.7388
Epoch 105/200
804/804 [==============================] - 0s 605us/step - loss: 0.5379 - accuracy: 0.7388
Epoch 106/200
804/804 [==============================] - 0s 595us/step - loss: 0.5378 - accuracy: 0.7396
Epoch 107/200
804/804 [==============================] - 0s 563us/step - loss: 0.5379 - accuracy: 0.7392
Epoch 108/200
804/804 [==============================] - 0s 592us/step - loss: 0.5379 - accuracy: 0.7392
Epoch 109/200
804/804 [==============================] - 0s 606us/step - loss: 0.5379 - accuracy: 0.7393
Epoch 110/200
804/804 [==============================] - 0s 576us/step - loss: 0.5377 - accuracy: 0.7393
Epoch 111/200
804/804 [==============================] - 0s 563us/step - loss: 0.5379 - accuracy: 0.7391
Epoch 112/200
804/804 [==============================] - 0s 607us/step - loss: 0.5374 - accuracy: 0.7391
Epoch 113/200
804/804 [==============================] - 0s 587us/step - loss: 0.5378 - accuracy: 0.7395
Epoch 114/200
804/804 [==============================] - 0s 579us/step - loss: 0.5377 - accuracy: 0.7393
Epoch 115/200
804/804 [==============================] - 0s 567us/step - loss: 0.5377 - accuracy: 0.7395
Epoch 116/200
804/804 [==============================] - 0s 590us/step - loss: 0.5373 - accuracy: 0.7400
Epoch 117/200
804/804 [==============================] - 0s 600us/step - loss: 0.5374 - accuracy: 0.7394
Epoch 118/200
804/804 [==============================] - 0s 590us/step - loss: 0.5380 - accuracy: 0.7381
Epoch 119/200
804/804 [==============================] - 0s 593us/step - loss: 0.5373 - accuracy: 0.7386
Epoch 120/200
804/804 [==============================] - 0s 575us/step - loss: 0.5376 - accuracy: 0.7395
Epoch 121/200
804/804 [==============================] - 1s 708us/step - loss: 0.5380 - accuracy: 0.7399
Epoch 122/200
804/804 [==============================] - 1s 675us/step - loss: 0.5380 - accuracy: 0.7389
Epoch 123/200
804/804 [==============================] - 0s 607us/step - loss: 0.5376 - accuracy: 0.7394
Epoch 124/200
804/804 [==============================] - 0s 579us/step - loss: 0.5371 - accuracy: 0.7398
Epoch 125/200
804/804 [==============================] - 0s 582us/step - loss: 0.5377 - accuracy: 0.7398
Epoch 126/200
804/804 [==============================] - 0s 570us/step - loss: 0.5372 - accuracy: 0.7399
Epoch 127/200
804/804 [==============================] - 0s 620us/step - loss: 0.5377 - accuracy: 0.7392
Epoch 128/200
804/804 [==============================] - 0s 570us/step - loss: 0.5372 - accuracy: 0.7387
Epoch 129/200
804/804 [==============================] - 0s 575us/step - loss: 0.5373 - accuracy: 0.7403
Epoch 130/200
804/804 [==============================] - 0s 589us/step - loss: 0.5369 - accuracy: 0.7397
Epoch 131/200
804/804 [==============================] - 0s 600us/step - loss: 0.5372 - accuracy: 0.7392
Epoch 132/200
804/804 [==============================] - 0s 575us/step - loss: 0.5370 - accuracy: 0.7393
Epoch 133/200
804/804 [==============================] - 0s 577us/step - loss: 0.5374 - accuracy: 0.7388
Epoch 134/200
804/804 [==============================] - 0s 572us/step - loss: 0.5367 - accuracy: 0.7393
Epoch 135/200
804/804 [==============================] - 0s 586us/step - loss: 0.5370 - accuracy: 0.7393
Epoch 136/200
804/804 [==============================] - 0s 567us/step - loss: 0.5371 - accuracy: 0.7393
Epoch 137/200
804/804 [==============================] - 0s 566us/step - loss: 0.5370 - accuracy: 0.7400
Epoch 138/200
804/804 [==============================] - 0s 604us/step - loss: 0.5372 - accuracy: 0.7396
Epoch 139/200
804/804 [==============================] - 0s 572us/step - loss: 0.5370 - accuracy: 0.7395
Epoch 140/200
804/804 [==============================] - 0s 584us/step - loss: 0.5370 - accuracy: 0.7387
Epoch 141/200
804/804 [==============================] - 0s 573us/step - loss: 0.5364 - accuracy: 0.7397
Epoch 142/200
804/804 [==============================] - 0s 585us/step - loss: 0.5370 - accuracy: 0.7395
Epoch 143/200
804/804 [==============================] - 0s 566us/step - loss: 0.5370 - accuracy: 0.7400
Epoch 144/200
804/804 [==============================] - 0s 576us/step - loss: 0.5366 - accuracy: 0.7401
Epoch 145/200
804/804 [==============================] - 0s 571us/step - loss: 0.5369 - accuracy: 0.7398
Epoch 146/200
804/804 [==============================] - 0s 590us/step - loss: 0.5369 - accuracy: 0.7391
Epoch 147/200
804/804 [==============================] - 0s 563us/step - loss: 0.5364 - accuracy: 0.7391
Epoch 148/200
804/804 [==============================] - 0s 568us/step - loss: 0.5369 - accuracy: 0.7392
Epoch 149/200
804/804 [==============================] - 0s 569us/step - loss: 0.5368 - accuracy: 0.7396
Epoch 150/200
804/804 [==============================] - 0s 568us/step - loss: 0.5366 - accuracy: 0.7388
Epoch 151/200
804/804 [==============================] - 0s 592us/step - loss: 0.5368 - accuracy: 0.7391
Epoch 152/200
804/804 [==============================] - 0s 579us/step - loss: 0.5366 - accuracy: 0.7407
Epoch 153/200
804/804 [==============================] - 0s 613us/step - loss: 0.5365 - accuracy: 0.7398
Epoch 154/200
804/804 [==============================] - 0s 573us/step - loss: 0.5370 - accuracy: 0.7390
Epoch 155/200
804/804 [==============================] - 0s 611us/step - loss: 0.5367 - accuracy: 0.7395
Epoch 156/200
804/804 [==============================] - 0s 582us/step - loss: 0.5366 - accuracy: 0.7393
Epoch 157/200

804/804 [==============================] - 0s 582us/step - loss: 0.5364 - accuracy: 0.7394
Epoch 158/200
804/804 [==============================] - 0s 572us/step - loss: 0.5367 - accuracy: 0.7407
Epoch 159/200
804/804 [==============================] - 0s 570us/step - loss: 0.5367 - accuracy: 0.7399
Epoch 160/200
804/804 [==============================] - 0s 568us/step - loss: 0.5365 - accuracy: 0.7403
Epoch 161/200
804/804 [==============================] - 0s 566us/step - loss: 0.5363 - accuracy: 0.7395
Epoch 162/200
804/804 [==============================] - 0s 578us/step - loss: 0.5367 - accuracy: 0.7399
Epoch 163/200
804/804 [==============================] - 0s 568us/step - loss: 0.5373 - accuracy: 0.7397
Epoch 164/200
804/804 [==============================] - 0s 578us/step - loss: 0.5364 - accuracy: 0.7402
Epoch 165/200
804/804 [==============================] - 0s 569us/step - loss: 0.5366 - accuracy: 0.7404
Epoch 166/200
804/804 [==============================] - 0s 580us/step - loss: 0.5365 - accuracy: 0.7398
Epoch 167/200
804/804 [==============================] - 0s 569us/step - loss: 0.5369 - accuracy: 0.7401
Epoch 168/200
804/804 [==============================] - 0s 580us/step - loss: 0.5364 - accuracy: 0.7399
Epoch 169/200
804/804 [==============================] - 0s 565us/step - loss: 0.5363 - accuracy: 0.7396
Epoch 170/200
804/804 [==============================] - 0s 579us/step - loss: 0.5362 - accuracy: 0.7399
Epoch 171/200
804/804 [==============================] - 0s 573us/step - loss: 0.5362 - accuracy: 0.7397
Epoch 172/200
804/804 [==============================] - 0s 563us/step - loss: 0.5361 - accuracy: 0.7393
Epoch 173/200
804/804 [==============================] - 0s 580us/step - loss: 0.5362 - accuracy: 0.7397
Epoch 174/200
804/804 [==============================] - 0s 573us/step - loss: 0.5362 - accuracy: 0.7400
Epoch 175/200
804/804 [==============================] - 0s 612us/step - loss: 0.5362 - accuracy: 0.7399
Epoch 176/200
804/804 [==============================] - 0s 576us/step - loss: 0.5363 - accuracy: 0.7396
Epoch 177/200
804/804 [==============================] - 0s 594us/step - loss: 0.5361 - accuracy: 0.7398
Epoch 178/200
804/804 [==============================] - 0s 568us/step - loss: 0.5368 - accuracy: 0.7403
Epoch 179/200
804/804 [==============================] - 0s 570us/step - loss: 0.5363 - accuracy: 0.7399
Epoch 180/200
804/804 [==============================] - 0s 574us/step - loss: 0.5359 - accuracy: 0.7400
Epoch 181/200
804/804 [==============================] - 0s 574us/step - loss: 0.5357 - accuracy: 0.7406
Epoch 182/200
804/804 [==============================] - 0s 563us/step - loss: 0.5361 - accuracy: 0.7398
Epoch 183/200
804/804 [==============================] - 0s 569us/step - loss: 0.5363 - accuracy: 0.7399
Epoch 184/200
804/804 [==============================] - 0s 590us/step - loss: 0.5363 - accuracy: 0.7398
Epoch 185/200
804/804 [==============================] - 0s 573us/step - loss: 0.5364 - accuracy: 0.7395
Epoch 186/200
804/804 [==============================] - 0s 570us/step - loss: 0.5358 - accuracy: 0.7398
Epoch 187/200
804/804 [==============================] - 0s 574us/step - loss: 0.5359 - accuracy: 0.7407
Epoch 188/200
804/804 [==============================] - 0s 584us/step - loss: 0.5361 - accuracy: 0.7391
Epoch 189/200
804/804 [==============================] - 0s 563us/step - loss: 0.5358 - accuracy: 0.7399
Epoch 190/200
804/804 [==============================] - 0s 574us/step - loss: 0.5358 - accuracy: 0.7400
Epoch 191/200
804/804 [==============================] - 0s 564us/step - loss: 0.5358 - accuracy: 0.7399
Epoch 192/200
804/804 [==============================] - 0s 579us/step - loss: 0.5360 - accuracy: 0.7400
Epoch 193/200
804/804 [==============================] - 0s 570us/step - loss: 0.5356 - accuracy: 0.7391
Epoch 194/200
804/804 [==============================] - 0s 559us/step - loss: 0.5360 - accuracy: 0.7402
Epoch 195/200
804/804 [==============================] - 0s 584us/step - loss: 0.5363 - accuracy: 0.7395
Epoch 196/200
804/804 [==============================] - 0s 563us/step - loss: 0.5357 - accuracy: 0.7401
Epoch 197/200
804/804 [==============================] - 0s 586us/step - loss: 0.5358 - accuracy: 0.7398
Epoch 198/200
804/804 [==============================] - 0s 561us/step - loss: 0.5358 - accuracy: 0.7401
Epoch 199/200
804/804 [==============================] - 0s 590us/step - loss: 0.5358 - accuracy: 0.7411
Epoch 200/200
804/804 [==============================] - 0s 563us/step - loss: 0.5359 - accuracy: 0.7399

In [144]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn3.evaluate(X_train_scaled,y_train,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

804/804 - 1s - loss: 0.5327 - accuracy: 0.7418
Loss: 0.532724142074585, Accuracy: 0.741836428642273

In [117]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=47))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))
    
    nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn

In [118]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

INFO:tensorflow:Reloading Oracle from existing project .\untitled_project\oracle.json

In [119]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 00m 17s]
val_accuracy: 0.7266472578048706

Best val_accuracy So Far: 0.7282798886299133
Total elapsed time: 00h 07m 46s
INFO:tensorflow:Oracle triggered exit

In [128]:
# Export our model to HDF5 file
nn1.save('AlphabetSoupCharity_Optimisation_m.h5')
nn2.save('AlphabetSoupCharity_Optimisation.h5')
nn3.save('AlphabetSoupCharity_Optimisation.h5')

In [129]:
open_model = tf.keras.models.load_model('AlphabetSoupCharity_Optimisation.h5')

In [131]:
open_model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_8 (Dense)              (None, 12)                576
_________________________________________________________________
dense_9 (Dense)              (None, 12)                156
_________________________________________________________________
dense_10 (Dense)             (None, 12)                156
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 13
=================================================================
Total params: 901
Trainable params: 901
Non-trainable params: 0
_________________________________________________________________